# Generated by Django 5.0.6 on 2024-07-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomoto',
            name='cilindraje',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='modelomoto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='modelomoto',
            name='potencia_maxima',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='modelomoto',
            name='tipo_motor',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='modelomoto',
            name='torque_maximo',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.modelomoto'),
        ),
    ]
