# Generated by Django 5.0.6 on 2024-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_modelomoto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomoto',
            name='potencia_maxima',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelomoto',
            name='torque_maximo',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
