# Generated by Django 5.0.6 on 2024-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_modelomoto_potencia_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomoto',
            name='tipo_motor',
            field=models.CharField(default='N/A', max_length=90),
        ),
    ]
