# Generated by Django 5.0.6 on 2024-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_modelomoto_tipo_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomoto',
            name='potencia_maxima',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
