# Generated by Django 5.0.6 on 2024-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_modelomoto_potencia_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomoto',
            name='tipo_motor',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
