# Generated by Django 5.0.6 on 2024-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_modelomoto_tipo_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomoto',
            name='tipo_motor',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
