# Generated by Django 5.0.6 on 2024-07-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Clientes',
        ),
    ]
